name: auto-shorts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours (adjust if you want)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Generate & Upload Short
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          NICHES: ${{ vars.NICHES }}
          FONT_PRESET: ${{ vars.FONT_PRESET }}
          SECONDS_PER_LINE: ${{ vars.SECONDS_PER_LINE }}
          CTA: ${{ vars.CTA }}
          YOUTUBE_PRIVACY: ${{ vars.YOUTUBE_PRIVACY }}
          ADD_CTA: ${{ vars.ADD_CTA }}
        run: python pipeline.py
